import type { Product, User, Order } from "./types"

export const mockProducts: Product[] = [
  {
    _id: "1",
    productName: "Classic Cotton T-Shirt",
    price: "999",
    brand: "FashionKart",
    category: "men",
    description: "Comfortable cotton t-shirt perfect for everyday wear",
    productImage: "/placeholder.svg?height=400&width=300&text=T-Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    rating: 4.5,
    reviews: 128,
    discount: 20,
    inStock: true,
  },
  {
    _id: "2",
    productName: "Denim Jacket",
    price: "2499",
    brand: "StyleCo",
    category: "women",
    description: "Trendy denim jacket for a casual look",
    productImage: "/placeholder.svg?height=400&width=300&text=Jacket",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue", "Black"],
    rating: 4.2,
    reviews: 89,
    discount: 15,
    inStock: true,
  },
  {
    _id: "3",
    productName: "Running Shoes",
    price: "3999",
    brand: "SportMax",
    category: "men",
    description: "Comfortable running shoes for your daily workout",
    productImage: "/placeholder.svg?height=400&width=300&text=Shoes",
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "White", "Red"],
    rating: 4.7,
    reviews: 256,
    discount: 25,
    inStock: true,
  },
  {
    _id: "4",
    productName: "Summer Dress",
    price: "1899",
    brand: "ElegantWear",
    category: "women",
    description: "Light and breezy summer dress",
    productImage: "/placeholder.svg?height=400&width=300&text=Dress",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Pink", "Blue", "Yellow"],
    rating: 4.3,
    reviews: 67,
    discount: 30,
    inStock: true,
  },
  {
    _id: "5",
    productName: "Kids Polo Shirt",
    price: "799",
    brand: "KidsStyle",
    category: "kids",
    description: "Comfortable polo shirt for kids",
    productImage: "/placeholder.svg?height=400&width=300&text=Kids+Polo",
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Red", "Blue", "Green"],
    rating: 4.4,
    reviews: 45,
    discount: 10,
    inStock: true,
  },
  {
    _id: "6",
    productName: "Moisturizing Cream",
    price: "1299",
    brand: "BeautyPlus",
    category: "beauty",
    description: "Hydrating moisturizing cream for all skin types",
    productImage: "/placeholder.svg?height=400&width=300&text=Cream",
    sizes: ["50ml", "100ml"],
    colors: [],
    rating: 4.6,
    reviews: 134,
    discount: 20,
    inStock: true,
  },
  {
    _id: "7",
    productName: "Decorative Cushion",
    price: "899",
    brand: "HomeDecor",
    category: "home",
    description: "Soft decorative cushion for your living room",
    productImage: "/placeholder.svg?height=400&width=300&text=Cushion",
    sizes: ["16x16", "18x18", "20x20"],
    colors: ["Beige", "Gray", "Blue"],
    rating: 4.1,
    reviews: 78,
    discount: 15,
    inStock: true,
  },
  {
    _id: "8",
    productName: "Leather Wallet",
    price: "1599",
    brand: "LeatherCraft",
    category: "men",
    description: "Genuine leather wallet with multiple compartments",
    productImage: "/placeholder.svg?height=400&width=300&text=Wallet",
    sizes: [],
    colors: ["Brown", "Black"],
    rating: 4.5,
    reviews: 92,
    discount: 0,
    inStock: true,
  },
]

export const mockUser: User = {
  _id: "user1",
  name: "John Doe",
  email: "john@example.com",
  phone: "9876543210",
  role: "consumer",
}

export const mockOrders: Order[] = [
  {
    _id: "order1",
    userId: "user1",
    products: [
      {
        productId: "1",
        quantity: 2,
        size: "M",
        price: 999,
      },
    ],
    totalAmount: 1998,
    status: "order_placed",
    shippingAddress: {
      street: "123 Main Street, Apt 4B",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400001",
      phone: "9876543210",
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
